-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-06-08 18:29:51 IST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



DROP TABLE ACTIVITIES CASCADE CONSTRAINTS 
;

DROP TABLE CONTENT CASCADE CONSTRAINTS 
;

DROP TABLE HISTORY CASCADE CONSTRAINTS 
;

DROP TABLE PAYMENT CASCADE CONSTRAINTS 
;

DROP TABLE SUBSCRIPTION CASCADE CONSTRAINTS 
;

DROP TABLE "USER" CASCADE CONSTRAINTS 
;

DROP TABLE user_activity CASCADE CONSTRAINTS 
;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE ACTIVITIES 
    ( 
     act_type     CHAR (1 CHAR)  NOT NULL , 
     act_date     DATE  NOT NULL , 
     act_desc     VARCHAR2 (50 CHAR)  NOT NULL , 
     act_feedback VARCHAR2 (50 CHAR) 
    ) 
;

COMMENT ON COLUMN ACTIVITIES.act_type IS 'id of activity' 
;

COMMENT ON COLUMN ACTIVITIES.act_date IS 'date the activity occured' 
;

COMMENT ON COLUMN ACTIVITIES.act_desc IS 'a breif desc of activity' 
;

COMMENT ON COLUMN ACTIVITIES.act_feedback IS 'feedback of the activityy' 
;

ALTER TABLE ACTIVITIES 
    ADD CONSTRAINT ACTIVITIES_PK PRIMARY KEY ( act_type, act_date ) ;

CREATE TABLE CONTENT 
    ( 
     cont_id      CHAR (32 CHAR)  NOT NULL , 
     cont_desc    VARCHAR2 (50 CHAR)  NOT NULL , 
     cont_address VARCHAR2 (100 CHAR)  NOT NULL 
    ) 
;

COMMENT ON COLUMN CONTENT.cont_id IS 'unique identifier of content' 
;

COMMENT ON COLUMN CONTENT.cont_desc IS 'breif desc of the content' 
;

COMMENT ON COLUMN CONTENT.cont_address IS 'address of the video/any file stored in s3 bucket or anyother storages.' 
;

ALTER TABLE CONTENT 
    ADD CONSTRAINT CONTENT_PK PRIMARY KEY ( cont_id ) ;

CREATE TABLE HISTORY 
    ( 
     hist_datetime DATE  NOT NULL , 
     cont_id       CHAR (32 CHAR)  NOT NULL , 
     user_id       CHAR (32 CHAR)  NOT NULL 
    ) 
;

COMMENT ON COLUMN HISTORY.hist_datetime IS 'datetime of user hitory' 
;

COMMENT ON COLUMN HISTORY.cont_id IS 'unique identifier of content' 
;

COMMENT ON COLUMN HISTORY.user_id IS 'unique identifier of usre' 
;

ALTER TABLE HISTORY 
    ADD CONSTRAINT HISTORY_PK PRIMARY KEY ( hist_datetime, cont_id, user_id ) ;

CREATE TABLE PAYMENT 
    ( 
     payment_id     CHAR (20 CHAR)  NOT NULL , 
     transaction_id CHAR (32 CHAR)  NOT NULL , 
     payment_amount NUMBER (4,2)  NOT NULL , 
     user_id        CHAR (32 CHAR)  NOT NULL 
    ) 
;

COMMENT ON COLUMN PAYMENT.payment_id IS 'unique pay,ent identifier' 
;

COMMENT ON COLUMN PAYMENT.transaction_id IS 'unique identifier of paymrny' 
;

COMMENT ON COLUMN PAYMENT.payment_amount IS 'payment amount for subscription ' 
;

COMMENT ON COLUMN PAYMENT.user_id IS 'unique identifier of usre' 
;

ALTER TABLE PAYMENT 
    ADD CONSTRAINT PAYMENT_PK PRIMARY KEY ( payment_id ) ;

CREATE TABLE SUBSCRIPTION 
    ( 
     plan_id       CHAR (1 CHAR)  NOT NULL , 
     plan_desc     VARCHAR2 (20 CHAR)  NOT NULL , 
     plan_features VARCHAR2 (100 CHAR)  NOT NULL , 
     plan_price    NUMBER (3,2)  NOT NULL 
    ) 
;

COMMENT ON COLUMN SUBSCRIPTION.plan_id IS 'different types of plan id' 
;

COMMENT ON COLUMN SUBSCRIPTION.plan_desc IS 'details of plan ' 
;

COMMENT ON COLUMN SUBSCRIPTION.plan_features IS 'various featurs for plan' 
;

COMMENT ON COLUMN SUBSCRIPTION.plan_price IS 'plan price' 
;

ALTER TABLE SUBSCRIPTION 
    ADD CONSTRAINT SUBSCRIPTION_PK PRIMARY KEY ( plan_id ) ;

CREATE TABLE "USER" 
    ( 
     user_id  CHAR (32 CHAR)  NOT NULL , 
     usr_flag CHAR (1 CHAR)  NOT NULL 
    ) 
;

COMMENT ON COLUMN "USER".user_id IS 'unique identifier of usre' 
;

COMMENT ON COLUMN "USER".usr_flag IS 'flag a user who is inactive - Y yes, N no' 
;

ALTER TABLE "USER" 
    ADD CONSTRAINT USER_PK PRIMARY KEY ( user_id ) ;

CREATE TABLE user_activity 
    ( 
     plan_id                CHAR (1 CHAR)  NOT NULL , 
     user_id                CHAR (32 CHAR)  NOT NULL , 
     datetime_lastsubscribe DATE  NOT NULL , 
     act_type               CHAR (1 CHAR)  NOT NULL , 
     act_date               DATE  NOT NULL 
    ) 
;

COMMENT ON COLUMN user_activity.plan_id IS 'different types of plan id' 
;

COMMENT ON COLUMN user_activity.user_id IS 'unique identifier of usre' 
;

COMMENT ON COLUMN user_activity.datetime_lastsubscribe IS 'date type of each record of user subscription plan' 
;

COMMENT ON COLUMN user_activity.act_type IS 'id of activity' 
;

COMMENT ON COLUMN user_activity.act_date IS 'date the activity occured' 
;

ALTER TABLE user_activity 
    ADD CONSTRAINT user_activity_PK PRIMARY KEY ( plan_id, user_id ) ;

ALTER TABLE HISTORY 
    ADD CONSTRAINT HISTORY_CONTENT_FK FOREIGN KEY 
    ( 
     cont_id
    ) 
    REFERENCES CONTENT 
    ( 
     cont_id
    ) 
;

ALTER TABLE HISTORY 
    ADD CONSTRAINT HISTORY_USER_FK FOREIGN KEY 
    ( 
     user_id
    ) 
    REFERENCES "USER" 
    ( 
     user_id
    ) 
;

ALTER TABLE PAYMENT 
    ADD CONSTRAINT PAYMENT_USER_FK FOREIGN KEY 
    ( 
     user_id
    ) 
    REFERENCES "USER" 
    ( 
     user_id
    ) 
;

ALTER TABLE user_activity 
    ADD CONSTRAINT user_activity_ACTIVITIES_FK FOREIGN KEY 
    ( 
     act_type,
     act_date
    ) 
    REFERENCES ACTIVITIES 
    ( 
     act_type,
     act_date
    ) 
;

ALTER TABLE user_activity 
    ADD CONSTRAINT user_activity_SUBSCRIPTION_FK FOREIGN KEY 
    ( 
     plan_id
    ) 
    REFERENCES SUBSCRIPTION 
    ( 
     plan_id
    ) 
;

ALTER TABLE user_activity 
    ADD CONSTRAINT user_activity_USER_FK FOREIGN KEY 
    ( 
     user_id
    ) 
    REFERENCES "USER" 
    ( 
     user_id
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             0
-- ALTER TABLE                             13
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
