/* here i created a sample table of useful info need for the churn rate
but in real worldscenario we use advance sql to query the required columns and create
thetable withat info 
example :  
    CREATE TABLE churn_analytics_data AS
    SELECT .... FROM TABLE1 T1 JOIN TABLE2 T2;
*/

CREATE TABLE churn_analytics_data (
    customer_id            NUMBER(10)      NOT NULL,
    plan_type              VARCHAR2(20)    NOT NULL,
    tenure_days            NUMBER(5)       NOT NULL,

    watch_hours_30d        NUMBER(8,2)     NOT NULL,
    login_count_30d        NUMBER(5)       NOT NULL,
    days_since_last_login  NUMBER(5)       NOT NULL,

    support_ticket_count   NUMBER(5)       DEFAULT 0,
    payment_failure_count  NUMBER(5)       DEFAULT 0,

    monthly_revenue        NUMBER(8,2)     NOT NULL,

    churn_flag             NUMBER(1)       NOT NULL
);
COMMENT ON COLUMN churn_analytics_data.customer_id 
    IS 'Unique identifier for each customer';
COMMENT ON COLUMN churn_analytics_data.plan_type 
    IS 'Type of subscription plan';
COMMENT ON COLUMN churn_analytics_data.tenure_days 
    IS 'Number of days the customer has been with the company';
COMMENT ON COLUMN churn_analytics_data.watch_hours_30d 
    IS 'Total hours watched by the customer in the last 30 days';
COMMENT ON COLUMN churn_analytics_data.login_count_30d 
    IS 'Number of logins by the customer in the last 30 days';
COMMENT ON COLUMN churn_analytics_data.days_since_last_login 
    IS 'Number of days since the customer last logged in';
COMMENT ON COLUMN churn_analytics_data.support_ticket_count 
    IS 'Total number of support tickets raised by the customer';
COMMENT ON COLUMN churn_analytics_data.payment_failure_count 
    IS 'Number of payment failures by the customer';
COMMENT ON COLUMN churn_analytics_data.monthly_revenue 
    IS 'Monthly revenue generated by the customer';
COMMENT ON COLUMN churn_analytics_data.churn_flag 
    IS 'Flag indicating if the customer has churned (1) or not (0)';
    
ALTER TABLE churn_analytics_data
    ADD CONSTRAINT churn_analytics_data_pk
        PRIMARY KEY (customer_id);
ALTER TABLE churn_analytics_data
    ADD CONSTRAINT churn_analytics_data_churn_ck
        CHECK (churn_flag IN (0,1));